### ISSUE TITLE
Classing or conditions

### ISSUE THREAD

**Issue by bart1** [enram/getRad#3]
I now class each error as "getRad_error_...." we could also go for c("getRad_error_....","getRad_error") more like httr2, see: https://github.com/r-lib/httr2/blob/5380f2107ea5a8e47def600e28009b5be1b8928a/R/resp-status.R#L82

**Comment by peterdesmet** [comment]
I would just go for one class. The way the error class string is made, makes it easy to search for it in the codebase.

If multiple classes are supported, I would only use it if it is a catch of an classed error of another package (cf. how one can append to object classes):

```R
c(“getRad_error_connection_issue”, “httr2_http_404”)
```

**Comment by bart1** [comment]
We can always add it later it should not break much code
