### ISSUE TITLE
Should the package version be part of the user agent string

### ISSUE THREAD

**Issue by bart1** [enram/getRad#4]
I try to consistently set the user agent so requests through the package can be tracked. Would it be useful to add the package version number or commit here? If so how to keep that up to date.

SVN used to have something called keywords that could do this, maybe git has something similar

**Comment by peterdesmet** [comment]
Do you do that (and if so how) for move2?

There is probably an easy function to access the installed package version (so it’s not hardcoded), I don’t know the best way to pass it. A `getRad@1.0` string?

**Comment by bart1** [comment]
great idea `getNamespaceVersion` can do this, might be a bit messy with dev version but I think that is ok
